//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TagInventory.WSRFID {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSRFIDDemoSoap", Namespace="http://tempuri.org/")]
    public partial class WSRFIDDemo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AvailableOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadRecuentoSimpleOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadRecuentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSRFIDDemo() {
            this.Url = "http://10.1.1.47:8088/WSRFIDDemo.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AvailableCompletedEventHandler AvailableCompleted;
        
        /// <remarks/>
        public event LoadRecuentoSimpleCompletedEventHandler LoadRecuentoSimpleCompleted;
        
        /// <remarks/>
        public event LoadRecuentoCompletedEventHandler LoadRecuentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Available", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Available() {
            object[] results = this.Invoke("Available", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AvailableAsync() {
            this.AvailableAsync(null);
        }
        
        /// <remarks/>
        public void AvailableAsync(object userState) {
            if ((this.AvailableOperationCompleted == null)) {
                this.AvailableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAvailableOperationCompleted);
            }
            this.InvokeAsync("Available", new object[0], this.AvailableOperationCompleted, userState);
        }
        
        private void OnAvailableOperationCompleted(object arg) {
            if ((this.AvailableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AvailableCompleted(this, new AvailableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadRecuentoSimple", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadRecuentoSimple(string XmlString) {
            object[] results = this.Invoke("LoadRecuentoSimple", new object[] {
                        XmlString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadRecuentoSimpleAsync(string XmlString) {
            this.LoadRecuentoSimpleAsync(XmlString, null);
        }
        
        /// <remarks/>
        public void LoadRecuentoSimpleAsync(string XmlString, object userState) {
            if ((this.LoadRecuentoSimpleOperationCompleted == null)) {
                this.LoadRecuentoSimpleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRecuentoSimpleOperationCompleted);
            }
            this.InvokeAsync("LoadRecuentoSimple", new object[] {
                        XmlString}, this.LoadRecuentoSimpleOperationCompleted, userState);
        }
        
        private void OnLoadRecuentoSimpleOperationCompleted(object arg) {
            if ((this.LoadRecuentoSimpleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRecuentoSimpleCompleted(this, new LoadRecuentoSimpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadRecuento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadRecuento(string XmlString) {
            object[] results = this.Invoke("LoadRecuento", new object[] {
                        XmlString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadRecuentoAsync(string XmlString) {
            this.LoadRecuentoAsync(XmlString, null);
        }
        
        /// <remarks/>
        public void LoadRecuentoAsync(string XmlString, object userState) {
            if ((this.LoadRecuentoOperationCompleted == null)) {
                this.LoadRecuentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRecuentoOperationCompleted);
            }
            this.InvokeAsync("LoadRecuento", new object[] {
                        XmlString}, this.LoadRecuentoOperationCompleted, userState);
        }
        
        private void OnLoadRecuentoOperationCompleted(object arg) {
            if ((this.LoadRecuentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRecuentoCompleted(this, new LoadRecuentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AvailableCompletedEventHandler(object sender, AvailableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AvailableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AvailableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoadRecuentoSimpleCompletedEventHandler(object sender, LoadRecuentoSimpleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadRecuentoSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadRecuentoSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoadRecuentoCompletedEventHandler(object sender, LoadRecuentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadRecuentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadRecuentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591